#####################################################
# A markdownreveal configuration file template. Visit
#   https://markdownreveal.readthedocs.io/
# for information on how to create your own.
#####################################################


#####################
# Style configuration

# #reveal.js base theme
theme: 'white'

# Markdownreveal style
style: 'https://github.com/markdownreveal/style-default/archive/master.tar.gz'

# Simple footer/header HTML such as 'Name | <a href="wewbsite">website</a>'
footer: ''
header: ''

# Math renderer plugin
katex: on
katex_version: 'latest'

# Emoji rendering
emoji_codes: on

#########################
# Reveal.js configuration

# A valid reveal.js version such as '3.4.1' ('latest' can be used too)
reveal_version: 'latest'

# Extra arguments for reveal.js
reveal_extra:
  controls: 'true'
  progress: 'true'
  slideNumber: 'false'
  history: 'true'
  keyboard: 'true'
  overview: 'true'
  center: 'true'
  showNotes: 'false'
  previewLinks: 'false'
  transition: 'slide'
  transitionSpeed: 'default'

###########################
# Pandoc configuration

# Extra arguments for pandoc
pandoc_extra:
  incremental: off

###########################
# Local paths configuration

# Styles
style_path: 'style'
style_logo: 'logo.svg'
style_background: 'background.svg'
style_warmup: 'warmup.svg'
style_custom_css: 'custom.css'

# Path, whithin the home directory to store local auto-generated content in
local_path: '.markdownreveal'
